apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: nginx-ingress
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    # Tên miền truy cập
    - host: tienhuynh.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-server-svc
                port:
                  number: 3000
